namespace S100Framework.REST.Models;

/// <summary>
/// Controls JSON output generated by replica edit payload builders.
/// </summary>
public sealed record ReplicaEditsJsonOptions
{
    /// <summary>
    /// Gets a value indicating whether generated JSON should be indented.
    /// </summary>
    public bool WriteIndented { get; init; }
}